[project]
name = "svribe"
version = "0.1.0"
description = "Svribe is your personal Discord Assistant that will transform a server into your small auto-organized notespace."
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "discord-py>=2.7.1",
    "google-genai>=2.7.0",
    "python-dotenv>=1.2.2",
]
